# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:


# # ASP.NET Core
# - script: dotnet build src/Pioneer.Blog/Pioneer.Blog.csproj --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'
# - script: dotnet publish src/Pioneer.Blog/Pioneer.Blog.csproj --output $(Build.ArtifactStagingDirectory)
#   displayName: 'Publish To Pipleline'

# Public Assets
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- script: |
    npm install --prefix src/app-client
    npm run build --prefix src/app-client
    
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: |
      src/Pioneer.Blog/wwwroot
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(System.DefaultWorkingDirectory)/src/Pioneer.Blog/wwwroot'
#     displayName: 'Publish Artifacts'

# # Publish all build artifacts
# - task: PublishBuildArtifacts@1
#   displayName: 'Publish Artifacts'